The Newsweek Page Clone
Davidosky007/News-Week-Clone pull request #5
Opened 2020-10-21 12:44 UTC by KinezaEnaelle

This project is about cloning the Newsweek page using HTML5/CSS3 and Bootstrap4. In this project, we used to flex and grid bootstrap classes to position items on the page.

2020-10-21 16:11 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @KinezaEnaelle  and @Davidosky007 . Thanks for submitting you project!

Great thing this project has and has done well:
:100: Great solid start!
:100: Nav, Main, and Footer contain all element needed
:100: Bootstrap is well implemented
:100: elements change in the different screen sizes

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The preview screenshot is not displaying in the README

- [ ] Use more Bootstrap classes. see inline

- [ ] subscribe and login are not aligned to the bottom
![image](https://user-images.githubusercontent.com/25774518/96742475-99198a80-1388-11eb-9a43-8c0e289fb130.png)

- [ ] Category element is not displaying in the correct position
![image](https://user-images.githubusercontent.com/25774518/96742665-c82ffc00-1388-11eb-944f-195877521e7f.png)

- [ ] my turn Images are not displaying properly
![image](https://user-images.githubusercontent.com/25774518/96742767-e0078000-1388-11eb-9126-d66247178bec.png)

- [ ] More stories are not looking as original
![image](https://user-images.githubusercontent.com/25774518/96742889-ff9ea880-1388-11eb-86a6-8d4e74f4e412.png)

- [ ] subscribe element is not centered in the column
![image](https://user-images.githubusercontent.com/25774518/96742980-1ba24a00-1389-11eb-898f-7770f1251205.png)

- [ ] subscribe and newsletter section are not displaying properly
![image](https://user-images.githubusercontent.com/25774518/96743168-51473300-1389-11eb-931e-8aca29cfe041.png)

- [ ] Footer is not displaying properly. Social icons out of place, margins/paddings are incorrect between elements and around the footer container
![image](https://user-images.githubusercontent.com/25774518/96744131-55278500-138a-11eb-8fbe-befa3133cec7.png)

- [ ] Navbar in tablet view is not showing menu
![image](https://user-images.githubusercontent.com/25774518/96743918-17c2f780-138a-11eb-9261-bd0fc59dd1ba.png)

- [ ] Signup element not displaying as original
![image](https://user-images.githubusercontent.com/25774518/96744242-78eacb00-138a-11eb-8c73-2a98fbdc5d23.png)

- [ ] Clone doesn't have margin left in tablet mode for some sections
![image](https://user-images.githubusercontent.com/25774518/96744357-99b32080-138a-11eb-9e87-2ce6a3eca077.png)

- [ ] Subscribe, Newsletter and footer are not displaying correctly in tablet view
![image](https://user-images.githubusercontent.com/25774518/96744533-c5360b00-138a-11eb-975b-615c2da30c2b.png)

- [ ] login icon is mission in navbar
![image](https://user-images.githubusercontent.com/25774518/96744663-e72f8d80-138a-11eb-8caa-9aca4e95d733.png)

- [ ] The order of the sections are not being followed in the mobile view
![image](https://user-images.githubusercontent.com/25774518/96744789-03cbc580-138b-11eb-88ca-593fb8acbc03.png)

- [ ] Unaligned elements in more stories
![image](https://user-images.githubusercontent.com/25774518/96744900-2231c100-138b-11eb-9707-0ce0d4e207d6.png)

- [ ] The debate section has unaligned elements, is not showing as original
![image](https://user-images.githubusercontent.com/25774518/96745043-4c837e80-138b-11eb-9390-4ec46f38004f.png)

- [ ] sign up is not displaying as original in mobile view
![image](https://user-images.githubusercontent.com/25774518/96745095-602ee500-138b-11eb-8ef6-d7da411005a3.png)

- [ ] In the magazine section is not displaying as original
![image](https://user-images.githubusercontent.com/25774518/96745191-79379600-138b-11eb-89dd-0fc4bc26d661.png)

- [ ] Elements in the editors pick section are not displaying as the original, there are no space between elements, elements are not well positioned, and images are not a similar size
![image](https://user-images.githubusercontent.com/25774518/96745338-a84e0780-138b-11eb-8490-a48771dc9c09.png)

- [ ] Elements in other section are not displaying correctly, elements are unaligned, the titles of the section doesn't have a similar style as the original
![image](https://user-images.githubusercontent.com/25774518/96745537-d9c6d300-138b-11eb-8603-2638b3d9bb2a.png)

- [ ] Subscribe section is not looking as original
![image](https://user-images.githubusercontent.com/25774518/96745627-f531de00-138b-11eb-9d40-e6e529bd7d71.png)

- [ ] Newsletter doesn't look as the original
![image](https://user-images.githubusercontent.com/25774518/96745698-07ac1780-138c-11eb-9c85-6be87859c11f.png)

- [ ] Footer doesn't look as the original
![image](https://user-images.githubusercontent.com/25774518/96745748-12ff4300-138c-11eb-9c2d-df2a82096d44.png)

### [OPTIONAL]  :yellow_circle:  

- [ ] Use [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) for `<nav>`, `<main>`, and `<article>`s.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-21 16:11 UTC, jubaan commented on assets/styles/main.css
> +
### [Comment]
- Just for your information: Boostrap already uses a `reset stylesheet`

2020-10-21 16:11 UTC, jubaan commented on assets/styles/main.css
> +}
- [ ] Bootstrap has a class for  `container` and `container-fluid`

- [ ] Bootstrap has class for `position-relative`

2020-10-21 16:11 UTC, jubaan commented on assets/styles/main.css
> +}
- [ ] Bootstrap has `border-0`

2020-10-21 16:11 UTC, jubaan commented on assets/styles/main.css
> +}
- [ ] Bootstrap has classes for white color.

2020-10-22 10:31 UTC, arslanbisharat requested changes
# Changes Requested 💀 

Hello Team, 👋 

Thank you for making changes. I would suggest some other changes.
**Please have a look below**

- [ ] [OPTIONAL] Too many font-size declarations (16), abstraction needed.

- [ ] Navbar on tablet mode has hamburger but its position it not aligned correctly.. Please have a look at the original page

- [ ] Your whole webpage has extra spacing around the edges. Please have a look there and work on it. . 

- [ ] On tablet mode, newsletter email input has more width than the original one. Please work on it. 
- [ ] On small screen, the Newsletter section doesn't look like the original one. Please work on it. 
- [ ] Navbar on small mode has hamburger but its position it not aligned correctly.. Please have a look at the original page

--------------------------------------------------------------------------------------------------

**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-22 10:31 UTC, arslanbisharat commented on assets/styles/main.css
> +  background-color: #e2e0e0 !important;
- [ ] PLEASE REMOVE !IMPORTANT

2020-10-22 10:31 UTC, arslanbisharat commented on README.md
> +# Project Name
Please remove this line

2020-10-22 10:31 UTC, arslanbisharat commented on README.md
> +# # News-Week-Clone
Please remove one #

2020-10-22 10:31 UTC, arslanbisharat commented on README.md
> +- Hat tip to anyone whose code was used
Whose code you used?

2020-10-22 12:08 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Please add the text in `alt` attribute. See the inline comment. ([Article](https://www.w3schools.com/tags/att_img_alt.asp) for better understanding)

### Newsletter
 - [ ] Please design the **Newsletter** like original landing page.

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://davidosky007.github.io/News-Week-Clone/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/96869088-6f478d00-1488-11eb-81dd-135d76a19d45.png)|![clone](https://user-images.githubusercontent.com/29689273/96869094-71a9e700-1488-11eb-910e-d73fc9a76dae.png)|

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-22 12:08 UTC, umairarshadbutt commented on index.html
> +                alt=""
- Add text in `alt` attribute
- Update it in all pages

2020-10-22 12:36 UTC, arslanbisharat approved these changes
# Approved :smile: 

Hello Developer, :wave:

I just reviewed your project and I am very happy to announce that your project is approved.
Congratulations on achieving this milestone in your career. :clap:

_I am looking forward to seeing your next project._

-----------------------------------------------------------------------------------------------

#### Regards,

#### Arslan Bisharat

#### slack: arslanbisharat

2020-10-22 12:40 UTC, merged